# Generated by Django 3.1.12 on 2021-06-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('bio', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.league')),
            ],
        ),
        migrations.CreateModel(
            name='Rostership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.contestant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.team')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.season'),
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.IntegerField(default=0)),
                ('contestant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.contestant')),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks', to='draft.draft')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.team')),
            ],
            options={
                'ordering': ['pick'],
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.league'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.season'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='teams',
            field=models.ManyToManyField(related_name='contestants', through='draft.Rostership', to='draft.Team'),
        ),
    ]
