# Generated by Django 3.1.12 on 2021-06-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20210617_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
