# Generated by Django 3.1.12 on 2021-06-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20210617_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='roses',
            field=models.IntegerField(default=0),
        ),
    ]
