# Generated by Django 3.1.13 on 2021-07-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_contestant_roses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['eliminated', '-roses', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
