# Generated by Django 3.1.13 on 2021-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_auto_20210710_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
